config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :tasks
  end
  devise_for :users
  root 'projects#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks , dependent: :destroy

  def badge_color
    case status
    when 'not-started'
      'secondary'
    when 'in-progress'
      'info'
    else
      'success'
    end 
  end

  def status
    return 'not-started' if tasks.none?

    if tasks.all? { |task| task.complete? }
      'complete'
    elsif tasks.any? { |task| task.in_progress? || task.complete? }
      'in-progress'
    else
      'not-started'
    end
  end

  def percent_complete
    return 0 if tasks.none?

    complete_tasks = tasks.select { |task| task.complete? }.count
    ((complete_tasks.to_f / tasks.count)*100).round
  end

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  validates :name, presence: true, uniqueness: { case_sensitive: false }, length: {maximum: 50}
  validates :status, inclusion: { in: ['not-started', 'in-progress', 'complete'] }

  STATUS_OPTIONS = [
    ['Not Started', 'not-started'],
    ['In Progress', 'in-progress'],
    ['Complete', 'complete']
  ]

  def badge_color
    case status
    when 'not-started'
      'secondary'
    when 'in-progress'
      'info'
    else
      'success'
    end 
  end

  def complete?
    status == 'complete'
  end

  def in_progress?
    status == 'in-progress'
  end

  def not_started?
    status == 'not-started'
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = current_user.projects
  end

  # GET /projects/1 or /projects/1.json
  def show
    @task = @project.tasks.build
  end

  # GET /projects/new
  def new
    @project = current_user.projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = current_user.projects.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_task, only: %i[ show edit update destroy ]


  # GET /tasks or /tasks.json
  def index
    @tasks = @project.tasks
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = @project.tasks.build
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = @project.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task.project }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task.project }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to @project, notice: "Task was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = @project.tasks.find(params[:id])
    end

    def set_project
      @project = current_user.projects.find(params[:project_id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:name, :description, :status)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white">
    <div class="container text-center">
      <small>Copyright &copy; <%= link_to "Ahmed Zaitoon", "https://github.com/Ahmed9711", class: "text-white"%></small>
    </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <% if user_signed_in? %>
      <%= link_to "Project Management App", projects_path, class: "navbar-brand" %>
    <% else %>
      <a class="navbar-brand" href="#">Project Management App</a>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Projects", projects_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= button_to "Sign out",  destroy_user_session_path, method: :delete, class: "btn btn-sm btn-outline-secondary" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManagementApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class = "bg-light">
    <%= render 'layouts/navigation' %>
    <div class="container pt-5 mb-5">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div>
    <%= form.submit class: "btn btn-primary mt-3" %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= project.user_id %>
  </p>

</div>

app/views/projects/edit.html.erb
<%= link_to "Back", @project, class: "btn btn-secondary mb-3" %>
<div class="card">
  <div class="card-body">
    <h2 class="card-title mb-4">
      <span>Editing Project</span>
    </h2>

    <%= render "form", project: @project %>
  </div>
</div>

app/views/projects/index.html.erb
<div class="card">
    <div class="card-body">
      <h2 class="card-title d-flex justify-content-between mb-4">
        <span>Projects</span>
          <%= link_to "New project", new_project_path , class: "btn btn-primary"%>
        </h2>

        <% @projects.each do |project| %>
          <%= link_to project , class: 'text-decoration-none' do %>
            <div class="card mb-3">
              <div class="card-body">
                <div class="mb-3">
                  <span class="badge text-bg-<%= project.badge_color%>"><%= project.status %></span>
                  <span class="text-secondary">
                    <small><%= project.percent_complete %>% complete</small>
                  </span>
                </div>
                <h5 class="card-title text-dark mt-3"><b><%= project.name %></b></h5>
                <p class="text-secondary"><%= project.description %></p>
              </div> 
            </div>
          <% end  %>
        <% end  %>
    </div>
</div>

app/views/projects/new.html.erb
 <%= link_to "Back", projects_path, class: "btn btn-secondary mb-3" %>
<div class="card">
  <div class="card-body">
    <h2 class="card-title mb-4">
      <span>New Project</span>
    </h2>

    <%= render "form", project: @project %>
  </div>
</div>

app/views/projects/show.html.erb
<%= link_to "Back", projects_path, class: "btn btn-secondary mb-3" %>
<div class="card">
    <div class="card-body">
      <h2 class="card-title d-flex justify-content-between">
        <span><%= @project.name %></span>
        <div>
          <%= link_to "Edit", edit_project_path(@project), class: "btn btn-light" %>
          <%= button_to "Delete", @project, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-dark" %>
        </div>
      </h2>

      <div class="mb-4">
        <h6>Add task</h6>
        <%= form_with(model: [@task.project, @task]) do |form| %>
          <% if @task.errors.any? %>
            <div style="color: red">
              <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

              <ul>
                <% @task.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <%= form.hidden_field :status, value: 'not-started'%>

          <div class = "input-group ">
            <%= form.text_field :name, class: "form-control", placeholder: "Enter Task name" %>
            <%= form.submit class: "btn btn-primary"%>
          </div>

        <% end %>
      </div>
      
      <h4>Tasks</h4>
      <% @project.tasks.each do |task| %>
        <% if task.persisted? %>
          <div class = "card mb-3">
            <div class = "card-body">
              <span class="badge text-bg-<%= task.badge_color%>"><%= task.status %></span>
              <h5 class="card-title d-flex justify-content-between">
                <span><%= task.name %></span>
                 <div>
                  <%= link_to "Edit", edit_project_task_path(@project, task), class: "btn btn-light btn-sm mb-1" %>
                  <%= button_to "Delete", [@project, task], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-dark btn-sm"  %>
                </div>
              </h5>
              <p><%= task.description %></p>
            </div>
          </div>
        <% end %>
      <% end %>  

    </div>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: [@project, task]) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :status, style: "display: block" %>
    <%= form.select :status, Task::STATUS_OPTIONS,{}, class: "form-select" %>
  </div>

  <div>
    <%= form.submit class: "btn btn-primary mt-3"%>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <p>
    <strong>Name:</strong>
    <%= task.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= task.description %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= task.status %>
  </p>

  <p>
    <strong>Project:</strong>
    <%= task.project_id %>
  </p>

</div>

app/views/tasks/edit.html.erb
<%= link_to "Back", @project, class: "btn btn-secondary mb-3" %>
<div class="card">
  <div class="card-body">
    <h2 class="card-title mb-4">
      <span>Editing task</span>
    </h2>

    <%= render "form", task: @task %>
  </div>
</div>

app/views/tasks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tasks</h1>

<div id="tasks">
  <% @tasks.each do |task| %>
    <%= render task %>
    <p>
      <%= link_to "Show this task", [task.project, task] %>
    </p>
  <% end %>
</div>

<%= link_to "New task", new_project_task_path %>

app/views/tasks/new.html.erb
<%= link_to "Back", @project, class: "btn btn-secondary mb-3" %>
<div class="card">
  <div class="card-body">
    <h2 class="card-title mb-4">
      <span>New task</span>
    </h2>

    <%= render "form", task: @task %>
  </div>
</div>

app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @task %>

<div>
  <%= link_to "Edit this task", edit_project_task_path(@task.project, @task) %> |
  <%= link_to "Back to tasks", @task.project %>

  <%= button_to "Destroy this task", [@task.project, @task], method: :delete %>
</div>

app/views/welcome/home.html.erb
<h1>Welcome to the Project Management App</h1>
<p>Find me in app/views/welcome/home.html.erb</p>
<%= button_to "Sign out", destroy_user_session_path, method: :delete %>